import {weaponProperties} from './weapon-mechanics.mjs';
import {activityFor,useActivity} from './services.mjs';
import {activityCost} from './mechanics.mjs';
export async function activityUseDialog(item,options={}){
  if(!item.actor?.isOwner)throw new Error('Abra um item de um ator sob seu controle.');
  const selected=activityFor(item,options.variantId);
  const quote=activityCost(item,selected.activity,item.actor.system,[...item.actor.items]);
  const choice=await foundry.applications.api.DialogV2.prompt({classes:['oprpg-native','op-dialog','op-flow'],position:{width:580},window:{title:'Usar atividade'},content:`<fieldset class="op-choice"><legend>${foundry.utils.escapeHTML(selected.name)}</legend><p>Custo calculado: <strong>${quote.cost} PP</strong> · Saldo: ${item.actor.system.power.value} PP</p>${selected.resolution.kind==='attack'?'<label>CR do alvo (vazio: resolver depois)<input name="targetCR" type="number" min="0"></label>':''}${item.type==='weapon'?'<label>Distância até o alvo (m, opcional)<input name="distance" type="number" min="0" step="any"></label>':''}${item.type==='technique'&&item.actor.system.power.value===0?`<label class="op-checkbox"><input name="overload" type="checkbox"> Usar sobrecarga: ${item.system.grade} nível(is) de exaustão</label>`:''}${selected.activity.activation==='powerful'?'<label class="op-checkbox"><input name="prepare" type="checkbox"> Preparar a técnica (ação + poderosa + PP)</label><label>Gatilho<input name="trigger"></label>':''}${item.actor.getFlag('oprpg-native','lifecycle')?.concentration?.prepared?'<label class="op-checkbox"><input name="release" type="checkbox"> Liberar a técnica preparada com reação</label>':''}${item.type==='weapon'&&item.actor.system.combat.state.specialAttacks>0?'<label class="op-checkbox"><input name="expertiseAttack" type="checkbox"> Ataque adicional de expertise (somente dano da arma/munição)</label>':''}${item.type==='weapon'?'<label>Atributo desta empunhadura<select name="attribute"><option value="">Padrão</option><option value="strength">Força</option><option value="dexterity">Destreza (exige Acuidade ou arma à distância)</option></select></label><label class="op-checkbox"><input name="twoHands" type="checkbox"> Usar duas mãos</label>':''}${item.type==='weapon'&&weaponProperties(item).throwing?'<label class="op-checkbox"><input name="throwing" type="checkbox"> Arremessar a arma</label>':''}<label>Benefício racial neste ataque<select name="racialBoost"><option value="">Nenhum / Sulong automático</option><option value="electro">Electro</option><option value="heat">Heat</option></select></label><label class="op-checkbox"><input type="checkbox" name="racialAlternative"> Uso racial sem bônus (até cinco usos por descanso longo)</label><p class="op-hint">O uso registra custos e ações. Confira o alvo e as exceções da fonte antes de confirmar.</p></fieldset>`,ok:{label:'Usar',callback:(_e,_b,app)=>{
    const fields=app.element.querySelector('form').elements;
    return {racialBoost:fields.racialBoost.value,racialAlternative:fields.racialAlternative.checked,attributeOverride:fields.attribute?.value||null,twoHands:fields.twoHands?.checked??false,throwing:fields.throwing?.checked??false,expertiseAttack:fields.expertiseAttack?.checked??false,targetActorUUID:[...(game.user.targets??[])].length===1?[...(game.user.targets??[])][0].actor?.uuid:null,targetCR:fields.targetCR?.value?Number(fields.targetCR.value):null,targetDistance:fields.distance?.value?Number(fields.distance.value):null,overload:fields.overload?.checked??false,prepare:fields.prepare?.checked??false,trigger:fields.trigger?.value??'',releasePrepared:fields.release?.checked??false};
  }}});
  if(!choice)return null;
  return useActivity(item,{...options,...choice});
}
