import {constructionQuote,MASTS,ENGINES} from './ship-building.mjs';
import {forceAnchoredMotion} from './anchor-motion.mjs';
import {mountedFall} from './mounted-fall.mjs';
import {resolveChaseComplication} from './chase-complications.mjs';
import {breathe,unarmedAttack,mountCreature,professionOperation} from './advanced-operations.mjs';
import {endConcentration,lifecycleOf} from './lifecycle.mjs';
import {useActivity} from './services.mjs';
import {resolveAgainstTargets,savingThrow} from './target-resolution.mjs';
import {applyExpertise} from './expertise.mjs';
import {operateDial,DIALS} from './dials.mjs';
import {travelDistance,forcedMarch,chaseDash,fallingDamage,contestedAction,escapeChase} from './exploration.mjs';
import {shipDamage,navalManoeuvre,navalAttack,shipConstruction,navalCollision,navalInitiative,protectShip,SHIP_SIZES,WOODS,CANNONS} from './naval.mjs';
import {composeMixedSpecies,setTransformation} from './species-specials.mjs';
const esc=value=>foundry.utils.escapeHTML(String(value??''));
const prompt=options=>foundry.applications.api.DialogV2.prompt({...options,classes:['oprpg-native','op-dialog','op-flow'],position:{width:680}});
const actors=()=>[...new Map([...(game.actors??[]),...(game.combat?.turns??[]).map(turn=>turn.actor).filter(Boolean)].filter(actor=>actor.isOwner).map(actor=>[actor.uuid,actor])).values()];
const select=(name,values,label,multiple=false)=>`<label>${label}<select name="${name}" ${multiple?'multiple':''}>${values.map(value=>`<option value="${esc(value.uuid??value.id)}" ${value.selected?'selected':''}>${esc(value.name)}</option>`).join('')}</select></label>`;
const number=(name,label,value=0)=>`<label>${label}<input name="${name}" type="number" min="0" step="any" value="${value}"></label>`;
const check=(name,label,checked=false)=>`<label class="op-checkbox"><input name="${name}" type="checkbox" ${checked?'checked':''}>${label}</label>`;
async function form(title,content,read){return prompt({window:{title},content:`<fieldset class="op-choice"><legend>${title}</legend>${content}</fieldset>`,ok:{label:'Confirmar',callback:(_e,_b,app)=>read(app.element.querySelector('form').elements)}});}
export async function openRulePanel(actor){
  if(!actor.isOwner)throw new Error('Sem permissão.');
  const operations=actor.type==='ship'?{shipConfig:'Configurar navegação e canhões',anchorMotion:'Movimento com âncora baixada',collision:'Colisão',protect:'Proteger navio',naval:'Manobras',shipDamage:'Dano e reparo',build:'Construção',cannon:'Canhões',initiative:'Iniciativa do capitão',structure:'Salvaguarda de estrutura'}:{actorConfig:'Configurar combate e grupo',unarmed:'Ataque desarmado',breath:'Respiração',mount:'Montar ou desmontar',mountedFall:'Queda da montaria',profession:'Característica profissional',concentration:'Concentração e preparação',resolve:'Resolver atividade e alvos',expertise:'Aplicar expertise',dial:'Operar um dial',travel:'Viagem e marcha',chase:'Perseguição',chaseComplication:'Complicação da perseguição',escapeChase:'Fuga da perseguição',fall:'Queda',contest:'Agarrar, empurrar ou escapar',mixed:'Criar espécie mestiça',transform:'Transformação'};
  const operation=await form('Operações de OP RPG',select('operation',Object.entries(operations).map(([id,name])=>({id,name})),'Mecânica'),fields=>fields.operation.value);if(!operation)return;
  const documents=actors();const find=uuid=>documents.find(value=>value.uuid===uuid);
  if(operation==='anchorMotion'){const choice=await form('Movimento com âncora baixada',number('knots','Velocidade ou tentativa de aceleração (nós)',6)+check('confirmed','Movimento confirmado pelo Narrador'),fields=>({knots:Number(fields.knots.value),confirmed:fields.confirmed.checked}));if(choice){const result=await forceAnchoredMotion(actor,choice);ui.notifications.info(`${result.received} de dano recebido · ${result.broken?'âncora desprendida':'âncora presa'}`);}}
  if(operation==='actorConfig'){
    const source=actor.toObject().system;
    const choice=await form('Combate e grupo',`<label>Grupo aliado (auras)<input name="affiliation" value="${esc(source.environment.affiliation)}"></label>`+select('size',[{id:'tiny',name:'Minúsculo'},{id:'small',name:'Pequeno'},{id:'medium',name:'Médio'},{id:'large',name:'Grande'},{id:'huge',name:'Enorme'},{id:'immense',name:'Imenso'}].map(value=>({...value,selected:value.id===source.environment.sizeCategory})),'Tamanho atual')+`<label>Dano desarmado sem Força<input name="unarmed" value="${esc(source.combat.unarmedDamage)}"></label>`+check('martial','Permitir passo marcial opcional 2d6',source.combat.martial2d6)+check('shield','Próximo de aliado com escudo de ferro',source.environment.nearShield)+check('heavyPoint','Zoan tem Heavy Point (Resistência dos Gigantes)',source.fruit.heavyPoint),fields=>({ 'system.environment.affiliation':fields.affiliation.value,'system.environment.sizeCategory':fields.size.value,'system.combat.unarmedDamage':fields.unarmed.value,'system.combat.martial2d6':fields.martial.checked,'system.environment.nearShield':fields.shield.checked,'system.fruit.heavyPoint':fields.heavyPoint.checked}));
    if(choice){if(!/^(1|1d[468]|1d10|1d12|2d6)$/.test(choice['system.combat.unarmedDamage']))throw new Error('Use 1 ou um dado válido de dano desarmado.');await actor.update(choice);}
  }
  if(operation==='unarmed'){const choice=await form('Ataque desarmado',check('adv','Vantagem')+check('dis','Desvantagem')+select('boost',[{id:'',name:'Nenhum (Sulong automático)'},{id:'electro',name:'Electro'},{id:'heat',name:'Heat'}],'Benefício racial')+check('alternative','Uso sem ação bônus'),fields=>({advantage:fields.adv.checked,disadvantage:fields.dis.checked,racialBoost:fields.boost.value,racialAlternative:fields.alternative.checked}));if(choice)await unarmedAttack(actor,choice);}
  if(operation==='mountedFall'){const choice=await form('Queda da montaria',select('kind',[{id:'forced',name:'Montaria movida contra a vontade'},{id:'riderProne',name:'Cavaleiro derrubado'},{id:'mountProne',name:'Montaria derrubada'}],'Situação')+check('reaction','Desmontar com reação quando a montaria cai')+check('confirmed','Situação confirmada pelo Narrador'),fields=>({kind:fields.kind.value,useReaction:fields.reaction.checked,confirmed:fields.confirmed.checked}));if(choice){const result=await mountedFall(actor,choice);ui.notifications.info(result.dismounted?'Desmontado: posicione a até 1,5 m da montaria.':'Permanece montado.');}}
  if(operation==='chaseComplication'){const choice=await form('Complicação da perseguição',select('environment',[{id:'urban',name:'Urbana'},{id:'nature',name:'Natureza'}],'Ambiente')+number('number','Resultado da tabela',actor.getFlag('oprpg-native','chaseComplication')?.number??11)+select('skill',[{id:'acrobatics',name:'Acrobacia'},{id:'athletics',name:'Atletismo'},{id:'intimidation',name:'Intimidação'},{id:'wisdom',name:'Sabedoria'}],'Teste quando há escolha')+number('movement','Movimento confirmado neste turno (m)')+check('coin','Dar uma moeda (urbana 8)')+check('avoid','Gastar 3 m para evitar espinhos (natureza 9)')+check('confirmed','Complicação e caminho confirmados pelo Narrador'),fields=>({environment:fields.environment.value,number:Number(fields.number.value),skill:fields.skill.value,movement:Number(fields.movement.value),coin:fields.coin.checked,avoid:fields.avoid.checked,confirmed:fields.confirmed.checked}));if(choice){const result=await resolveChaseComplication(actor,choice);ui.notifications.info(result.narrator?'O Narrador escolhe uma criatura nativa.':result.pendingMovement?'Ataque do guarda pendente: resolva quando o movimento chegar a 6 m.':result.success?'Complicação superada.':'Consequências aplicadas; confira a posição no mapa.');}}
  if(operation==='breath'){const choice=await form('Respiração',select('mode',[{id:'hold',name:'Prender a respiração'},{id:'breathe',name:'Voltar a respirar'}],'Escolha')+check('air','A criatura tem acesso ao ar'),fields=>({hold:fields.mode.value==='hold',airConfirmed:fields.air.checked}));if(choice){const until=await breathe(actor,choice);if(until)ui.notifications.info(`Fôlego disponível por ${until-game.time.worldTime} segundos.`);}}
  if(operation==='mount'){const choice=await form('Montaria',select('mount',documents.filter(value=>value!==actor&&value.type!=='ship'),'Criatura')+check('dismount','Desmontar')+check('controlled','Controlada: treinada e não inteligente (Narrador)')+check('confirmed','Consente, anatomia e tamanho adequados, a até 1,5 m'),fields=>({mount:find(fields.mount.value),dismount:fields.dismount.checked,controlled:fields.controlled.checked,confirmed:fields.confirmed.checked}));if(choice)await mountCreature(actor,choice.mount,choice);}
  if(operation==='profession'){
    const items=actor.items.filter(value=>value.type==='profession');
    const choice=await form('Característica profissional',select('item',items,'Profissão')+select('skill',Object.entries(actor.system.skills).map(([id])=>({id,name:id})),'Perícia da característica')+number('cost','Custo predeterminado em Belly')+number('difficulty','CD predeterminada',15)+number('die','Faces do dado de recuperação (0: não usa)',6)+check('restoration','Aplicar dado de recuperação')+select('target',documents.filter(value=>value.type!=='ship'),'Alvo da recuperação')+select('resource',[{id:'vitality',name:'PV'},{id:'power',name:'PP'}],'Recurso')+check('confirmed','Ferramentas, duração e requisitos conferidos com o Narrador'),fields=>({item:items.find(value=>value.uuid===fields.item.value),skill:fields.skill.value,cost:Number(fields.cost.value),difficulty:Number(fields.difficulty.value),die:Number(fields.die.value),restoration:fields.restoration.checked,target:find(fields.target.value),resource:fields.resource.value,confirmed:fields.confirmed.checked}));if(choice)await professionOperation(choice.item,choice);
  }
  if(operation==='shipConfig'){
    const source=actor.system.naval;
    const choice=await form('Navegação e armamento',select('captain',documents.filter(value=>value.type!=='ship').map(value=>({uuid:value.uuid,name:value.name,selected:value.uuid===source.captainUUID})),'Capitão')+number('maximum','Velocidade máxima (nós)',source.maximumKnots)+number('current','Velocidade atual (nós)',source.currentKnots)+`<label>Corrente a favor/contra (nós)<input type="number" step="any" name="bonus" value="${source.currentBonusKnots}"></label><label>Canhões (um modelo por linha)<textarea name="cannons">${source.cannons.map(slot=>(CANNONS[slot.model]?.name??slot.model)+(slot.destroyed?' destruído':'')).join('\n')}</textarea></label><p>Modelos: Comum, Aprimorado, Superior, Longo Alcance, Energia. Acrescente “destruído” após o modelo quando aplicável.</p>`+check('kairo','Casco de Kairoseki',source.kairoseki),fields=>({captain:fields.captain.value,maximum:Number(fields.maximum.value),current:Number(fields.current.value),bonus:Number(fields.bonus.value),cannons:fields.cannons.value,kairo:fields.kairo.checked}));
    if(choice){const cannons=choice.cannons.split(/\r?\n/).map(value=>value.trim()).filter(Boolean).map(line=>({model:Object.keys(CANNONS).find(key=>[key,CANNONS[key].name].some(name=>name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/^canhao (de )?/,'')===line.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s*destruido/g,'').trim().replace(/^canhao (de )?/,''))),destroyed:/destru[ií]do/i.test(line)}));if(cannons.some(slot=>!CANNONS[slot.model]))throw new Error('Modelo de canhão desconhecido.');if(choice.current>choice.maximum)throw new Error('A velocidade atual excede o máximo.');await actor.update({'system.naval.captainUUID':choice.captain,'system.naval.maximumKnots':choice.maximum,'system.naval.currentKnots':choice.current,'system.naval.currentBonusKnots':choice.bonus,'system.naval.cannons':cannons,'system.naval.kairoseki':choice.kairo});}
  }
  if(operation==='collision'){const choice=await form('Colisão naval',select('target',documents.filter(value=>value.type==='ship'&&value!==actor),'Navio atingido')+check('confirmed','Colisão e velocidades confirmadas'),fields=>({target:find(fields.target.value),confirmed:fields.confirmed.checked}));if(choice)await navalCollision(actor,choice.target,choice);}
  if(operation==='concentration'){
    const held=lifecycleOf(actor).concentration;const choice=await form('Concentração',`<p>${esc(held?.name??'Nenhuma concentração ativa')}</p>${select('mode',[{id:'end',name:'Encerrar concentração'},{id:'release',name:'Liberar técnica preparada'}],'Escolha')}`,fields=>fields.mode.value);
    if(choice==='end')await endConcentration(actor);else if(choice==='release'){const item=actor.items.find(item=>item.uuid===held?.itemUUID);if(!item)throw new Error('A fonte preparada não está na ficha.');await useActivity(item,{requestId:foundry.utils.randomID(),releasePrepared:true});}
  }
  if(operation==='resolve'){
    if(!game.user.isGM)throw new Error('O Narrador confirma alvos e condições.');
    const use=actor.getFlag('oprpg-native','lastActivity'),item=use?.unarmed?{uuid:null,actor,name:'Ataque desarmado'}:actor.items.find(item=>item.uuid===use?.itemUUID);if(!item||use.prepared)throw new Error('Use ou libere a atividade antes de resolver.');
    const choice=await form('Resolver atividade',select('targets',documents.filter(actor=>actor.type!=='ship'),'Alvos',true)+number('damage','Dano/cura já rolado (uma rolagem para todos)')+(use.extraDamageComponents??[]).map((value,index)=>number(`extra-${index}`,`Dano adicional ${value.type}, rolado separadamente`)).join('')+select('coverage',[{id:'none',name:'Sem cobertura'},{id:'half',name:'Meia cobertura (+2)'},{id:'threeQuarters',name:'Cobertura superior (+5)'},{id:'total',name:'Cobertura total'}],'Maior cobertura dos alvos')+check('area','Efeito de área alcança os alvos')+check('legendary','Permitir resistência lendária nos alvos'),fields=>({targets:Array.from(fields.targets.selectedOptions,option=>find(option.value)),damage:Number(fields.damage.value),extraDamage:(use.extraDamageComponents??[]).map((value,index)=>Number(fields.namedItem(`extra-${index}`).value)),coverage:fields.coverage.value,area:fields.area.checked,legendary:fields.legendary.checked}));
    if(choice)await resolveAgainstTargets(item,use,{...choice,legendaryTargets:choice.legendary?choice.targets.map(actor=>actor.uuid):[]});
  }
  if(operation==='expertise'){
    const use=actor.getFlag('oprpg-native','lastActivity'),item=actor.items.find(item=>item.uuid===use?.itemUUID);if(!item)throw new Error('Registre um crítico natural com arma.');
    const choice=await form('Expertise de arma',select('targets',documents.filter(actor=>actor.type!=='ship'),'Alvo(s)',true)+select('choice',[{id:'damage',name:'Dano adicional'},{id:'move',name:'Empurrar/puxar'}],'Quando a expertise oferece escolha')+select('temporary',[{id:'replace',name:'Substituir PV temporários'},{id:'keep',name:'Manter PV temporários'}],'PV temporários')+check('near','Todos os alvos de área estão a até 3 metros'),fields=>({targets:Array.from(fields.targets.selectedOptions,option=>find(option.value)),choice:fields.choice.value,temporaryChoice:fields.temporary.value,confirmArea:fields.near.checked}));
    if(choice)await applyExpertise(item,{...choice,target:choice.targets[0]});
  }
  if(operation==='dial'){
    const items=actor.items.filter(item=>item.system.dial?.model);const choice=await form('Dials',select('item',items,'Dial')+select('mode',[{id:'charge',name:'Iniciar absorção'},{id:'finishCharge',name:'Concluir absorção'},{id:'prepare',name:'Preparar absorção rápida'},{id:'rapid',name:'Absorver impacto com reação'},{id:'release',name:'Liberar'},{id:'sync',name:'Sincronizar Control Dial'},{id:'control',name:'Acionar dial remoto'},{id:'wall',name:'Eisen: criar parede'},{id:'retract',name:'Eisen: recolher parede'},{id:'wallDamage',name:'Eisen: dano na parede'}],'Operação')+select('remote',documents.flatMap(value=>value.items.filter(item=>item.system.dial?.model)),'Dial remoto')+select('remoteMode',[{id:'charge',name:'Absorção'},{id:'release',name:'Liberação'}],'Operação remota (ação + bônus)')+number('remoteDistance','Distância do dial remoto (m)')+number('damage','Dano incidente')+select('type',[{id:'fire',name:'Fogo'},{id:'cold',name:'Frio'},{id:'lightning',name:'Elétrico'},{id:'bludgeoning',name:'Contundente'}],'Tipo incidente')+'<label>Conteúdo/composto<input name="cargo"></label><label>Gatilho<input name="trigger"></label>'+check('contact','A fonte de absorção/material está presente')+check('wind','Vento forte (Breath/Flavor)'),fields=>({item:items.find(item=>item.uuid===fields.item.value),operation:fields.mode.value,damage:Number(fields.damage.value),damageType:fields.type.value,cargo:fields.cargo.value,trigger:fields.trigger.value,contactConfirmed:fields.contact.checked,strongWind:fields.wind.checked,remoteItem:documents.flatMap(value=>value.items).find(value=>value.uuid===fields.remote.value),remoteOperation:fields.remoteMode.value,distance:Number(fields.remoteDistance.value)}));if(choice){const result=await operateDial(choice.item,choice);if(result?.remaining!==undefined)ui.notifications.info(`${result.absorbed} absorvido; aplique ${result.remaining} de dano restante.`);}
  }
  if(operation==='travel'){
    const choice=await form('Viagem',select('pace',[{id:'fast',name:'Rápido'},{id:'normal',name:'Normal'},{id:'slow',name:'Lento'}],'Ritmo')+number('hours','Horas')+number('days','Dias')+check('difficult','Terreno difícil')+check('march','Resolver marcha forçada deste personagem'),fields=>({pace:fields.pace.value,hours:Number(fields.hours.value),days:Number(fields.days.value),difficult:fields.difficult.checked,march:fields.march.checked}));if(choice){const result=travelDistance(choice);ui.notifications.info(`${result.kilometers} km · Percepção passiva ${result.perception}`);if(choice.march&&choice.hours>8)await forcedMarch(actor,choice);}
  }
  if(operation==='chase'){const choice=await form('Perseguição','<label>Identificador da perseguição<input name="id" required></label>',fields=>fields.id.value);if(choice){const result=await chaseDash(actor,{chaseId:choice});ui.notifications.info(`${result.count} disparada(s) · salvaguarda e complicação serão resolvidas ao encerrar o turno.`);}}
  if(operation==='protect'){const choice=await form('Proteger navio',select('protector',documents.filter(value=>value.type!=='ship'&&value.system.progression.level>=8),'Tripulante (nível 8+)')+'<p>Consome o turno do protetor. CR +1 até seu próximo turno, máximo +3 por navio.</p>',fields=>find(fields.protector.value));if(choice)await protectShip(choice,actor);}
  if(operation==='escapeChase'){const choice=await form('Fugir da perseguição',select('pursuers',documents.filter(value=>value!==actor&&value.type!=='ship'),'Perseguidores',true)+check('sight','O líder manteve a presa à vista')+check('adv','Circunstância concede vantagem')+check('dis','Circunstância concede desvantagem'),fields=>({pursuers:Array.from(fields.pursuers.selectedOptions,option=>find(option.value)),leaderHasSight:fields.sight.checked,advantage:fields.adv.checked,disadvantage:fields.dis.checked}));if(choice){const result=await escapeChase(actor,choice.pursuers,choice);ui.notifications.info(result.escaped?'A presa escapou.':'A perseguição continua.');}}
  if(operation==='fall'){const choice=await form('Queda',number('meters','Altura (m)'),fields=>Number(fields.meters.value));if(choice!==null)await fallingDamage(actor,{meters:choice});}
  if(operation==='contest'){const choice=await form('Manobra resistida',select('target',documents.filter(value=>value.type!=='ship'&&value!==actor),'Alvo')+select('kind',[{id:'grapple',name:'Agarrar'},{id:'shoveProne',name:'Derrubar'},{id:'shoveAway',name:'Empurrar'},{id:'escape',name:'Escapar'}],'Manobra')+select('defense',[{id:'athletics',name:'Atletismo'},{id:'acrobatics',name:'Acrobacia'}],'Defesa escolhida pelo alvo')+check('allowed','Tamanho e alcance atendem à regra'),fields=>({target:find(fields.target.value),kind:fields.kind.value,defense:fields.defense.value,sizeAllowed:fields.allowed.checked}));if(choice){const result=await contestedAction(actor,choice.target,choice);ui.notifications.info(result.success?'Manobra bem-sucedida.':'Empate ou falha: situação preservada.');}}
  if(operation==='transform'){const choice=await form('Transformação',select('mode',[{id:'sulong',name:'Forma Sulong'},{id:'end',name:'Encerrar forma'}],'Forma')+check('moon','Ativar: lua cheia observada por seis segundos. Encerrar: um turno sem olhar para a lua e ação para cobrir os olhos.'),fields=>({mode:fields.mode.value,confirmed:fields.moon.checked}));if(choice)await setTransformation(actor,choice);}
  if(operation==='mixed'){if(!game.user.isGM)throw new Error('O Narrador cria a espécie mestiça.');const species=game.items.filter(item=>item.type==='species');const choice=await form('Espécie mestiça',select('first',species,'Primeira origem')+select('second',species,'Segunda origem')+'<label>Benefício da primeira origem<input name="benefit1" required></label><label>Benefício da segunda origem<input name="benefit2" required></label><label>Dificuldade<input name="difficulty" required></label><label>Dificuldade adicional (benefício restrito)<input name="extra"></label>'+check('traits','Benefícios, dificuldade adicional e ancestralidade foram escolhidos conforme p.27'),fields=>({first:species.find(item=>item.uuid===fields.first.value),second:species.find(item=>item.uuid===fields.second.value),traitsConfirmed:fields.traits.checked,firstBenefit:fields.benefit1.value,secondBenefit:fields.benefit2.value,difficulty:fields.difficulty.value,extraDifficulty:fields.extra.value}));if(choice)await composeMixedSpecies(choice);}
  if(operation==='naval'){const choice=await form('Manobra naval',select('action',[{id:'speed',name:'Acelerar/desacelerar'},{id:'port',name:'Bombordo'},{id:'starboard',name:'Estibordo'},{id:'anchor',name:'Baixar/recolher âncora'}],'Manobra')+number('knots','Velocidade escolhida (nós)',2)+check('confirmed','Capitão/navegador/timoneiro no comando'),fields=>({action:fields.action.value,knots:Number(fields.knots.value),steersmanConfirmed:fields.confirmed.checked}));if(choice)await navalManoeuvre(actor,choice);}
  if(operation==='shipDamage'){const choice=await form('Dano/reparo naval',number('amount','Quantidade')+check('repair','Aplicar como reparo'),fields=>({amount:Number(fields.amount.value),repair:fields.repair.checked}));if(choice)await shipDamage(actor,choice.amount,choice);}
  if(operation==='build'){
   const choice=await form('Construção de navio',select('size',Object.entries(SHIP_SIZES).map(([id,value])=>({id,name:value.name})),'Tamanho')+select('wood',Object.entries(WOODS).map(([id,value])=>({id,name:value.name})),'Madeira')+select('mast',Object.entries(MASTS).map(([id,value])=>({id,name:value.name})),'Mastro')+number('mastCount','Quantidade de mastros',1)+select('engine',Object.entries(ENGINES).map(([id,value])=>({id,name:value.name})),'Motor')+select('fortification',[{id:'none',name:'Nenhuma'},{id:'steel',name:'Aço'},{id:'tempered',name:'Aço temperado'}],'Fortificação')+check('kairoseki','Revestir com kairoseki')+check('apply','Registrar estrutura e velocidade nesta ficha'),fields=>({size:fields.size.value,wood:fields.wood.value,mast:fields.mast.value,mastCount:Number(fields.mastCount.value),engine:fields.engine.value,fortification:fields.fortification.value,kairoseki:fields.kairoseki.checked,apply:fields.apply.checked}));
   if(choice){const result=constructionQuote(choice);await prompt({window:{title:'Orçamento naval'},content:`<ul>${result.parts.map(part=>`<li>${esc(part.name)} · ${part.cost.toLocaleString('pt-BR')} ฿ · ${part.days.toFixed(2)} dias</li>`).join('')}</ul><p>Total: ${result.total.toLocaleString('pt-BR')} ฿ · ${result.sequentialDays.toFixed(2)} dias em sequência</p><p>Não inclui cômodos, equipamentos nem mão de obra extra. Motores exigem sala, combustível e tripulantes conforme a fonte.</p>`,ok:{label:'Conferido'}});if(choice.apply)await actor.update({'system.naval.size':choice.size,'system.naval.wood':choice.wood,'system.naval.fortification':choice.fortification,'system.naval.kairoseki':choice.kairoseki,'system.naval.maximumKnots':result.maximumKnots,'system.structure.size':result.name,'system.vitality.max':result.hp,...(actor.system.vitality.max===0?{'system.vitality.value':result.hp}:{}),'system.defense.rating':result.cr});}
  }
  if(operation==='initiative'||operation==='structure'){const captain=await fromUuid(actor.system.naval.captainUUID);if(!captain?.isOwner)throw new Error('Defina o capitão.');if(operation==='initiative')await navalInitiative(actor);else {const dc=await form('Salvaguarda de estrutura',number('dc','CD',17),fields=>Number(fields.dc.value));if(dc!==null)await savingThrow(captain,'will',dc);}}
  if(operation==='cannon'){
    const choice=await form('Ataque de canhão',select('cannon',actor.system.naval.cannons.map((slot,index)=>({id:String(index),name:`${index+1} · ${CANNONS[slot.model]?.name??slot.model}`})),'Canhão')+select('target',documents.filter(value=>value.type==='ship'&&value!==actor),'Navio alvo')+select('ammo',actor.items.filter(item=>item.type==='equipment'),'Munição/bateria')+number('distance','Distância (m)')+number('dexterity','Maior modificador de Destreza dos atiradores')+select('strategy',[{id:'attack',name:'Ataque'},{id:'bombardment',name:'Bombardeio'},{id:'test',name:'Tiros de Teste'}],'Estratégia')+check('crew','Efetivo e apontamento confirmados')+check('energy','Energia preparada por dez minutos')+number('prior','Dano anterior bem-sucedido'),fields=>({cannonIndex:Number(fields.cannon.value),target:find(fields.target.value),ammunitionItem:fields.ammo.value.split('.').at(-1),distance:Number(fields.distance.value),gunnersDexterity:Number(fields.dexterity.value),strategy:fields.strategy.value,crewConfirmed:fields.crew.checked,preparedEnergy:fields.energy.checked,hitDamage:Number(fields.prior.value)}));if(choice)await navalAttack(actor,choice);
  }
}
